DROP TABLE IF EXISTS policy_sub CASCADE;
DROP TABLE IF EXISTS blocked_service_sub CASCADE;
DROP TABLE IF EXISTS present_data CASCADE;
DROP TABLE IF EXISTS notification_allow CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS family_apply CASCADE;
DROP TABLE IF EXISTS family_sub CASCADE;
DROP TABLE IF EXISTS family CASCADE;
DROP TABLE IF EXISTS subscription CASCADE;
DROP TABLE IF EXISTS social_account CASCADE;
DROP TABLE IF EXISTS member CASCADE;

DROP TABLE IF EXISTS block_policy CASCADE;
DROP TABLE IF EXISTS app_blocked_service CASCADE;
DROP TABLE IF EXISTS plan CASCADE;
DROP TABLE IF EXISTS outbox_event CASCADE;
